# makefile for shape editor example

.cpp.obj:
        tcc -c $*.cpp

all : keyread.exe shed.exe

keyread.exe : keyread.cpp
	tcc keyread.cpp
	
shed.exe: shed.obj ellipse.obj polygon.obj bgi.obj shape.obj shlist.obj
  tcc shed.obj ellipse.obj polygon.obj bgi.obj shape.obj shlist.obj graphics.lib

shed.obj : polygon.hpp shape.hpp bgi.hpp ellipse.hpp circbox.hpp doskey.hpp shlist.hpp shed.cpp
ellipse.obj : ellipse.hpp shape.hpp bgi.hpp ellipse.cpp
polygon.obj : polygon.hpp shape.hpp bgi.hpp polygon.cpp
bgi.obj : bgi.hpp bgi.cpp
shape.obj : shape.hpp bgi.hpp shape.cpp
shlist.obj : shlist.hpp shape.hpp bgi.hpp shlist.cpp
